# Change these first
owner: owid # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Our World In Data
    url: https://ourworldindata.org/
  - name: Data catalog (garden)
    url: https://catalog.ourworldindata.org/catalog-garden.feather
  - name: Admin
    url: https://owid.cloud/admin/charts/

status-website:
  baseUrl: /status
  title: Our World In Data - Status
